def lis2cnt(lis):
    #converts list to counter list(accepts instances of classes)
    counter = [[], []]
    for x in lis:                                     #for each item/value in list
        if not x in [y for y in counter[0]]:       #if it is not in output ID list
            counter[0].append(x)                          #add it
            counter[1].append(0)                          #and add 0 counter to second list

        ind = [y for y in counter[0]].index(x)     #get its index
        counter[1][ind] += 1                             #and increase its counter by 1
    
    return counter

cmsn_rewe_dict = {
         1: [
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_horn', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', 'imp_horn', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', ],
         ],
         2: [
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_horn', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', 'imp_horn', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', ],
         ],
         3: [
           ['met_nugget', 'met_nugget', ],
           ['met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_ingot', ],
           ['met_nugget', 'imp_horn', ],
           ['met_nugget', 'imp_horn', 'imp_bone', ],
           ['met_nugget', 'imp_horn', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'met_nugget', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_ingot', ],
           ['imp_horn', 'imp_horn', ],
           ['imp_horn', 'imp_horn', 'imp_bone', ],
           ['imp_horn', 'imp_horn', 'met_ingot', ],
         ],
         4: [
           ['met_nugget', 'met_nugget', ],
           ['met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_ingot', ],
           ['met_nugget', 'imp_horn', ],
           ['met_nugget', 'imp_horn', 'imp_bone', ],
           ['met_nugget', 'imp_horn', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'met_nugget', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_ingot', ],
           ['imp_horn', 'imp_horn', ],
           ['imp_horn', 'imp_horn', 'imp_bone', ],
           ['imp_horn', 'imp_horn', 'met_ingot', ],
         ],
         5: [
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_heart', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'imp_heart', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'imp_horn', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'imp_horn', 'met_ingot', ],
           ['met_nugget', 'imp_horn', 'imp_heart', ],
           ['met_nugget', 'imp_horn', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_horn', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_horn', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_horn', 'imp_heart', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_horn', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'imp_heart', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['imp_horn', 'imp_horn', 'imp_bone', 'imp_bone', ],
           ['imp_horn', 'imp_horn', 'met_ingot', ],
           ['imp_horn', 'imp_horn', 'imp_heart', ],
           ['imp_horn', 'imp_horn', 'met_nugget', 'met_nugget', 'imp_bone', ],
         ],
         6: [
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_heart', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'imp_heart', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'imp_horn', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'imp_horn', 'met_ingot', ],
           ['met_nugget', 'imp_horn', 'imp_heart', ],
           ['met_nugget', 'imp_horn', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_horn', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_horn', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_horn', 'imp_heart', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'imp_horn', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'imp_bone', 'imp_bone', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'imp_heart', ],
           ['met_nugget', 'met_nugget', 'imp_horn', 'met_nugget', 'met_nugget', 'imp_bone', ],
           ['imp_horn', 'imp_horn', 'imp_bone', 'imp_bone', ],
           ['imp_horn', 'imp_horn', 'met_ingot', ],
           ['imp_horn', 'imp_horn', 'imp_heart', ],
           ['imp_horn', 'imp_horn', 'met_nugget', 'met_nugget', 'imp_bone', ],
         ],
         7: [
           ['met_nugget', 'imp_bone', ],
           ['met_nugget', 'imp_bone', 'met_nugget', ],
           ['met_nugget', 'imp_bone', 'wood_plank', ],
           ['met_nugget', 'met_ingot', ],
           ['met_nugget', 'met_ingot', 'met_nugget', ],
           ['met_nugget', 'met_ingot', 'wood_plank', ],
           ['met_nugget', 'met_nugget', 'met_nugget', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'wood_plank', ],
           ['imp_bone', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'met_nugget', ],
           ['imp_bone', 'met_ingot', 'wood_plank', ],
           ['met_ingot', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'met_nugget', ],
           ['met_ingot', 'met_ingot', 'wood_plank', ],
         ],
         8: [
           ['met_nugget', 'imp_bone', ],
           ['met_nugget', 'imp_bone', 'met_nugget', ],
           ['met_nugget', 'imp_bone', 'wood_plank', ],
           ['met_nugget', 'met_ingot', ],
           ['met_nugget', 'met_ingot', 'met_nugget', ],
           ['met_nugget', 'met_ingot', 'wood_plank', ],
           ['met_nugget', 'met_nugget', 'met_nugget', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'wood_plank', ],
           ['imp_bone', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'met_nugget', ],
           ['imp_bone', 'met_ingot', 'wood_plank', ],
           ['met_ingot', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'met_nugget', ],
           ['met_ingot', 'met_ingot', 'wood_plank', ],
         ],
         9: [
           ['imp_bone', 'imp_bone', 'imp_bone', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'imp_bone', 'imp_bone', 'wood_plank', ],
           ['imp_bone', 'imp_bone', 'imp_bone', 'met_ingot', ],
           ['imp_bone', 'imp_bone', 'imp_bone', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'imp_bone', 'met_ingot', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'imp_bone', 'met_ingot', 'wood_plank', ],
           ['imp_bone', 'imp_bone', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'imp_bone', 'met_ingot', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'met_ingot', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'met_ingot', 'wood_plank', ],
           ['imp_bone', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'imp_heart', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'imp_heart', 'wood_plank', ],
           ['imp_bone', 'imp_heart', 'met_ingot', ],
           ['imp_bone', 'imp_heart', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['imp_heart', 'met_nugget', 'met_nugget', ],
           ['imp_heart', 'wood_plank', ],
           ['imp_heart', 'met_ingot', ],
           ['imp_heart', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['met_ingot', 'met_ingot', 'met_nugget', 'met_nugget', ],
           ['met_ingot', 'met_ingot', 'wood_plank', ],
           ['met_ingot', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'met_nugget', 'met_nugget', 'met_nugget', ],
         ],
         10: [
           ['imp_bone', 'imp_bone', 'imp_bone', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'imp_bone', 'imp_bone', 'wood_plank', ],
           ['imp_bone', 'imp_bone', 'imp_bone', 'met_ingot', ],
           ['imp_bone', 'imp_bone', 'imp_bone', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'imp_bone', 'met_ingot', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'imp_bone', 'met_ingot', 'wood_plank', ],
           ['imp_bone', 'imp_bone', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'imp_bone', 'met_ingot', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'met_ingot', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'met_ingot', 'wood_plank', ],
           ['imp_bone', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'imp_heart', 'met_nugget', 'met_nugget', ],
           ['imp_bone', 'imp_heart', 'wood_plank', ],
           ['imp_bone', 'imp_heart', 'met_ingot', ],
           ['imp_bone', 'imp_heart', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['imp_heart', 'met_nugget', 'met_nugget', ],
           ['imp_heart', 'wood_plank', ],
           ['imp_heart', 'met_ingot', ],
           ['imp_heart', 'met_nugget', 'met_nugget', 'met_nugget', ],
           ['met_ingot', 'met_ingot', 'met_nugget', 'met_nugget', ],
           ['met_ingot', 'met_ingot', 'wood_plank', ],
           ['met_ingot', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'met_nugget', 'met_nugget', 'met_nugget', ],
         ],
         11: [
           ['imp_bone', 'met_ingot', 'met_ingot', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'met_ingot', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'met_ingot', 'imp_soul', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'met_ingot', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'met_ingot', 'met_ingot', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'met_ingot', 'wood_plank', 'wood_plank', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'imp_soul', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'met_ingot', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'wood_plank', 'wood_plank', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'imp_heart', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'imp_soul', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'imp_heart', 'met_ingot', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'wood_plank', 'wood_plank', 'imp_soul', ],
           ['imp_heart', 'imp_heart', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['imp_heart', 'imp_heart', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['imp_heart', 'imp_heart', 'imp_soul', 'imp_soul', ],
           ['imp_heart', 'imp_heart', 'met_ingot', 'met_ingot', ],
           ['imp_heart', 'imp_heart', 'met_ingot', 'imp_soul', ],
           ['imp_heart', 'imp_heart', 'wood_plank', 'wood_plank', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'imp_soul', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'met_ingot', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'wood_plank', 'wood_plank', 'imp_soul', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'imp_soul', 'imp_soul', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'met_ingot', 'met_ingot', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'met_ingot', 'imp_soul', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'wood_plank', 'wood_plank', 'imp_soul', ],
         ],
         12: [
           ['imp_bone', 'met_ingot', 'met_ingot', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'met_ingot', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'met_ingot', 'imp_soul', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'met_ingot', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'met_ingot', 'met_ingot', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'met_ingot', 'wood_plank', 'wood_plank', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'imp_soul', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'met_ingot', 'met_ingot', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'met_ingot', 'imp_soul', ],
           ['imp_bone', 'met_ingot', 'imp_heart', 'wood_plank', 'wood_plank', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'imp_heart', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'imp_soul', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'imp_heart', 'met_ingot', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'wood_plank', 'wood_plank', 'imp_soul', ],
           ['imp_heart', 'imp_heart', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['imp_heart', 'imp_heart', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['imp_heart', 'imp_heart', 'imp_soul', 'imp_soul', ],
           ['imp_heart', 'imp_heart', 'met_ingot', 'met_ingot', ],
           ['imp_heart', 'imp_heart', 'met_ingot', 'imp_soul', ],
           ['imp_heart', 'imp_heart', 'wood_plank', 'wood_plank', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'imp_soul', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'met_ingot', 'imp_soul', ],
           ['met_ingot', 'imp_heart', 'imp_heart', 'wood_plank', 'wood_plank', 'imp_soul', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'wood_plank', 'met_ingot', 'met_ingot', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'met_nugget', 'imp_soul', 'imp_soul', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'imp_soul', 'imp_soul', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'met_ingot', 'met_ingot', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'met_ingot', 'imp_soul', ],
           ['met_nugget', 'imp_bone', 'met_ingot', 'imp_heart', 'wood_plank', 'wood_plank', 'imp_soul', ],
         ],
         13: [
           ['met_scrap', 'met_nugget', ],
           ['met_scrap', 'met_nugget', 'met_scrap', ],
           ['met_scrap', 'met_nugget', 'met_ingot', ],
           ['met_scrap', 'dem_bone', ],
           ['met_scrap', 'dem_bone', 'met_scrap', ],
           ['met_scrap', 'dem_bone', 'met_ingot', ],
           ['met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_scrap', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_scrap', 'met_scrap', 'met_scrap', 'met_ingot', ],
           ['met_nugget', 'dem_bone', ],
           ['met_nugget', 'dem_bone', 'met_scrap', ],
           ['met_nugget', 'dem_bone', 'met_ingot', ],
           ['dem_bone', 'dem_bone', ],
           ['dem_bone', 'dem_bone', 'met_scrap', ],
           ['dem_bone', 'dem_bone', 'met_ingot', ],
         ],
         14: [
           ['met_scrap', 'met_nugget', ],
           ['met_scrap', 'met_nugget', 'met_scrap', ],
           ['met_scrap', 'met_nugget', 'met_ingot', ],
           ['met_scrap', 'dem_bone', ],
           ['met_scrap', 'dem_bone', 'met_scrap', ],
           ['met_scrap', 'dem_bone', 'met_ingot', ],
           ['met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_scrap', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_scrap', 'met_scrap', 'met_scrap', 'met_ingot', ],
           ['met_nugget', 'dem_bone', ],
           ['met_nugget', 'dem_bone', 'met_scrap', ],
           ['met_nugget', 'dem_bone', 'met_ingot', ],
           ['dem_bone', 'dem_bone', ],
           ['dem_bone', 'dem_bone', 'met_scrap', ],
           ['dem_bone', 'dem_bone', 'met_ingot', ],
         ],
         15: [
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'dem_skin', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'met_nugget', 'dem_bone', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'dem_bone', 'dem_skin', ],
           ['met_nugget', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'dem_bone', 'met_ingot', ],
           ['met_nugget', 'dem_bone', 'dem_skin', ],
           ['met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'met_scrap', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'met_scrap', 'met_nugget', 'dem_bone', 'met_ingot', ],
           ['met_nugget', 'met_scrap', 'met_nugget', 'dem_bone', 'dem_skin', ],
           ['met_nugget', 'met_scrap', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_scrap', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', ],
           ['met_scrap', 'met_nugget', 'dem_bone', 'met_ingot', ],
           ['met_scrap', 'met_nugget', 'dem_bone', 'dem_skin', ],
           ['met_scrap', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['dem_bone', 'dem_bone', 'met_scrap', 'met_scrap', ],
           ['dem_bone', 'dem_bone', 'met_ingot', ],
           ['dem_bone', 'dem_bone', 'dem_skin', ],
           ['dem_bone', 'dem_bone', 'met_scrap', 'met_scrap', 'met_scrap', ],
         ],
         16: [
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'dem_skin', ],
           ['met_nugget', 'met_nugget', 'met_nugget', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'met_nugget', 'dem_bone', 'met_ingot', ],
           ['met_nugget', 'met_nugget', 'dem_bone', 'dem_skin', ],
           ['met_nugget', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'dem_bone', 'met_ingot', ],
           ['met_nugget', 'dem_bone', 'dem_skin', ],
           ['met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'met_scrap', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', ],
           ['met_nugget', 'met_scrap', 'met_nugget', 'dem_bone', 'met_ingot', ],
           ['met_nugget', 'met_scrap', 'met_nugget', 'dem_bone', 'dem_skin', ],
           ['met_nugget', 'met_scrap', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['met_scrap', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', ],
           ['met_scrap', 'met_nugget', 'dem_bone', 'met_ingot', ],
           ['met_scrap', 'met_nugget', 'dem_bone', 'dem_skin', ],
           ['met_scrap', 'met_nugget', 'dem_bone', 'met_scrap', 'met_scrap', 'met_scrap', ],
           ['dem_bone', 'dem_bone', 'met_scrap', 'met_scrap', ],
           ['dem_bone', 'dem_bone', 'met_ingot', ],
           ['dem_bone', 'dem_bone', 'dem_skin', ],
           ['dem_bone', 'dem_bone', 'met_scrap', 'met_scrap', 'met_scrap', ],
         ],
         17: [
           ['met_ingot', 'dem_skin', ],
           ['met_ingot', 'dem_skin', 'met_ingot', ],
           ['met_ingot', 'dem_skin', 'met_rod', ],
           ['met_ingot', 'met_ingot', 'dem_skin', ],
           ['met_ingot', 'met_ingot', 'dem_skin', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'dem_skin', 'met_rod', ],
           ['met_ingot', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['dem_skin', 'met_ingot', 'dem_skin', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'met_ingot', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'met_rod', ],
           ['met_ingot', 'dem_skin', 'met_ingot', 'dem_skin', ],
           ['met_ingot', 'dem_skin', 'met_ingot', 'dem_skin', 'met_rod', ],
         ],
         18: [
           ['met_ingot', 'dem_skin', ],
           ['met_ingot', 'dem_skin', 'met_ingot', ],
           ['met_ingot', 'dem_skin', 'met_rod', ],
           ['met_ingot', 'met_ingot', 'dem_skin', ],
           ['met_ingot', 'met_ingot', 'dem_skin', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'dem_skin', 'met_rod', ],
           ['met_ingot', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['dem_skin', 'met_ingot', 'dem_skin', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'met_ingot', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'met_rod', ],
           ['met_ingot', 'dem_skin', 'met_ingot', 'dem_skin', ],
           ['met_ingot', 'dem_skin', 'met_ingot', 'dem_skin', 'met_rod', ],
         ],
         19: [
           ['dem_skin', 'dem_skin', 'dem_skin', 'met_ingot', 'met_ingot', ],
           ['dem_skin', 'dem_skin', 'dem_skin', 'met_rod', ],
           ['dem_skin', 'dem_skin', 'dem_skin', 'dem_heart', ],
           ['dem_skin', 'dem_skin', 'dem_skin', 'met_scrap', 'met_scrap', 'met_ingot', ],
           ['dem_skin', 'dem_skin', 'met_ingot', 'dem_skin', 'met_ingot', 'met_ingot', ],
           ['dem_skin', 'dem_skin', 'met_ingot', 'dem_skin', 'met_rod', ],
           ['dem_skin', 'dem_skin', 'met_ingot', 'dem_skin', 'dem_heart', ],
           ['dem_skin', 'dem_skin', 'met_ingot', 'dem_skin', 'met_scrap', 'met_scrap', 'met_ingot', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'met_ingot', 'met_ingot', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'met_rod', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'dem_heart', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'met_scrap', 'met_scrap', 'met_ingot', ],
           ['met_ingot', 'dem_skin', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'dem_skin', 'met_rod', ],
           ['met_ingot', 'dem_skin', 'dem_heart', ],
           ['met_ingot', 'dem_skin', 'met_scrap', 'met_scrap', 'met_ingot', ],
         ],
         20: [
           ['dem_skin', 'dem_skin', 'dem_skin', 'met_ingot', 'met_ingot', ],
           ['dem_skin', 'dem_skin', 'dem_skin', 'met_rod', ],
           ['dem_skin', 'dem_skin', 'dem_skin', 'dem_heart', ],
           ['dem_skin', 'dem_skin', 'dem_skin', 'met_scrap', 'met_scrap', 'met_ingot', ],
           ['dem_skin', 'dem_skin', 'met_ingot', 'dem_skin', 'met_ingot', 'met_ingot', ],
           ['dem_skin', 'dem_skin', 'met_ingot', 'dem_skin', 'met_rod', ],
           ['dem_skin', 'dem_skin', 'met_ingot', 'dem_skin', 'dem_heart', ],
           ['dem_skin', 'dem_skin', 'met_ingot', 'dem_skin', 'met_scrap', 'met_scrap', 'met_ingot', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'met_ingot', 'met_ingot', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'met_rod', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'dem_heart', ],
           ['dem_skin', 'met_ingot', 'dem_skin', 'met_scrap', 'met_scrap', 'met_ingot', ],
           ['met_ingot', 'dem_skin', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'dem_skin', 'met_rod', ],
           ['met_ingot', 'dem_skin', 'dem_heart', ],
           ['met_ingot', 'dem_skin', 'met_scrap', 'met_scrap', 'met_ingot', ],
         ],
         21: [
           ['met_ingot', 'met_rod', ],
           ['met_ingot', 'met_rod', 'met_rod', ],
           ['met_ingot', 'met_rod', 'dem_hskin', ],
           ['met_ingot', 'dem_heart', ],
           ['met_ingot', 'dem_heart', 'met_rod', ],
           ['met_ingot', 'dem_heart', 'dem_hskin', ],
           ['met_ingot', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['met_ingot', 'met_ingot', 'met_ingot', 'dem_hskin', ],
           ['met_rod', 'dem_heart', ],
           ['met_rod', 'dem_heart', 'met_rod', ],
           ['met_rod', 'dem_heart', 'dem_hskin', ],
           ['dem_heart', 'dem_heart', ],
           ['dem_heart', 'dem_heart', 'met_rod', ],
           ['dem_heart', 'dem_heart', 'dem_hskin', ],
         ],
         22: [
           ['met_ingot', 'met_rod', ],
           ['met_ingot', 'met_rod', 'met_rod', ],
           ['met_ingot', 'met_rod', 'dem_hskin', ],
           ['met_ingot', 'dem_heart', ],
           ['met_ingot', 'dem_heart', 'met_rod', ],
           ['met_ingot', 'dem_heart', 'dem_hskin', ],
           ['met_ingot', 'met_ingot', 'met_ingot', ],
           ['met_ingot', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['met_ingot', 'met_ingot', 'met_ingot', 'dem_hskin', ],
           ['met_rod', 'dem_heart', ],
           ['met_rod', 'dem_heart', 'met_rod', ],
           ['met_rod', 'dem_heart', 'dem_hskin', ],
           ['dem_heart', 'dem_heart', ],
           ['dem_heart', 'dem_heart', 'met_rod', ],
           ['dem_heart', 'dem_heart', 'dem_hskin', ],
         ],
         23: [
           ['met_rod', 'met_rod', 'met_rod', 'met_rod', 'met_rod', ],
           ['met_rod', 'met_rod', 'met_rod', 'dem_hskin', ],
           ['met_rod', 'met_rod', 'met_rod', 'dem_soul', ],
           ['met_rod', 'met_rod', 'met_rod', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['met_rod', 'met_rod', 'dem_heart', 'met_rod', 'met_rod', ],
           ['met_rod', 'met_rod', 'dem_heart', 'dem_hskin', ],
           ['met_rod', 'met_rod', 'dem_heart', 'dem_soul', ],
           ['met_rod', 'met_rod', 'dem_heart', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['met_rod', 'dem_heart', 'met_rod', 'met_rod', ],
           ['met_rod', 'dem_heart', 'dem_hskin', ],
           ['met_rod', 'dem_heart', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['met_rod', 'met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_rod', ],
           ['met_rod', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', ],
           ['met_rod', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', ],
           ['met_rod', 'met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_rod', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['dem_heart', 'dem_heart', 'met_rod', 'met_rod', ],
           ['dem_heart', 'dem_heart', 'dem_hskin', ],
           ['dem_heart', 'dem_heart', 'dem_soul', ],
           ['dem_heart', 'dem_heart', 'met_ingot', 'met_ingot', 'met_rod', ],
         ],
         24: [
           ['met_rod', 'met_rod', 'met_rod', 'met_rod', 'met_rod', ],
           ['met_rod', 'met_rod', 'met_rod', 'dem_hskin', ],
           ['met_rod', 'met_rod', 'met_rod', 'dem_soul', ],
           ['met_rod', 'met_rod', 'met_rod', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['met_rod', 'met_rod', 'dem_heart', 'met_rod', 'met_rod', ],
           ['met_rod', 'met_rod', 'dem_heart', 'dem_hskin', ],
           ['met_rod', 'met_rod', 'dem_heart', 'dem_soul', ],
           ['met_rod', 'met_rod', 'dem_heart', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['met_rod', 'dem_heart', 'met_rod', 'met_rod', ],
           ['met_rod', 'dem_heart', 'dem_hskin', ],
           ['met_rod', 'dem_heart', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['met_rod', 'met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_rod', ],
           ['met_rod', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', ],
           ['met_rod', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', ],
           ['met_rod', 'met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_rod', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_ingot', 'met_rod', ],
           ['dem_heart', 'dem_heart', 'met_rod', 'met_rod', ],
           ['dem_heart', 'dem_heart', 'dem_hskin', ],
           ['dem_heart', 'dem_heart', 'dem_soul', ],
           ['dem_heart', 'dem_heart', 'met_ingot', 'met_ingot', 'met_rod', ],
         ],
         25: [
           ['met_rod', 'dem_heart', 'dem_heart', 'dem_hskin', 'dem_soul', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'dem_heart', 'met_rod', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'dem_heart', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'dem_heart', 'dem_soul', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'dem_heart', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'dem_heart', 'dem_hskin', 'dem_hskin', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_soul', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_hskin', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_soul', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_hskin', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_soul', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_hskin', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_soul', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_hskin', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
         ],
         26: [
           ['met_rod', 'dem_heart', 'dem_heart', 'dem_hskin', 'dem_soul', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'dem_heart', 'met_rod', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'dem_heart', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'dem_heart', 'dem_soul', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'dem_heart', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'dem_heart', 'dem_hskin', 'dem_hskin', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_soul', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_hskin', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_soul', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_hskin', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_soul', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_hskin', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_soul', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_rod', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_soul', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
           ['met_ingot', 'met_rod', 'dem_heart', 'met_ingot', 'met_rod', 'dem_heart', 'dem_hskin', 'dem_hskin', 'met_ingot', 'met_rod', 'dem_hskin', 'dem_soul', ],
         ],
}


for key in cmsn_rewe_dict:
    for y, lis in enumerate(cmsn_rewe_dict[key]):
        cmsn_rewe_dict[key][y] = lis2cnt(lis)


spacer = '    '
with open('cmsn_rewe_dict+.txt', 'w') as file:
    out = 'cmsn_enem_dict = {\n'
    for key in cmsn_rewe_dict:
        out += spacer + f'{key}: '
        for y, lis in enumerate(cmsn_rewe_dict[key]):
            if y != 0:
                out += spacer + '     '
            out += '['
            for x in lis:
                out += str(x)
                out = out + ', ' if lis.index(x) != len(lis)-1 else out
            out += '], \n'
        out += 2*spacer + '],\n'
    out += '}'
        
    file.write(out)
    
    
