#created using script(besides '1' and '2') Pushover
cmsn_enem_dict = {
    '1': [['Servant', [imp_2], [2]], ['Hindrance', [imp_2, imp_1], [1, 2]], ['Lowlife', [imp_1], [5]] ],
    '2': [['Lowlife', [imp_1], [8]], ['Lowlife', [imp_1], [7]], ['Lowlife', [imp_1], [6]],
          ['Servant', [imp_2], [4]],
          ['Hindrance', [imp_2, imp_1], [3, 5]], ['Hindrance', [imp_2, imp_1], [3, 4]] ],
    '3': [['Imp', [imp_3], [2]], ['Imp', [imp_3, imp_2], [2, 1]], ['Imp', [imp_3, imp_1], [2, 4]], 
          ['Servant', [imp_2], [7]], ['Servant', [imp_2], [8]], 
          ['Hindrance', [imp_2, imp_1], [4, 8]], ['Hindrance', [imp_2, imp_1], [4, 7]], 
          ['Hindrance', [imp_2, imp_1], [3, 10]], ['Hindrance', [imp_2, imp_1], [3, 9]], 
          ['Lowlife', [imp_1], [14]], ['Lowlife', [imp_1], [13]] ],
    '4': [[['Imp', imp_3], [5]], ['Imp', [imp_3], [4]], 
          ['Commoner', [imp_3, imp_2, imp_1], [2, 6, 8]], ['Commoner', [imp_3, imp_2, imp_1], [2, 6, 7]], 
          ['Commoner', [imp_3, imp_2, imp_1], [2, 5, 8]], ['Commoner', [imp_3, imp_2, imp_1], [2, 5, 7]], 
          ['Deserter', [imp_3, imp_2], [3, 6]], ['Deserter', [imp_3, imp_2], [3, 5]], 
          ['Small patrol', [imp_3, imp_1], [3, 8]], ['Small patrol', [imp_3, imp_1], [3, 7]], 
          ['Servant', [imp_2], [11]], ['Servant', [imp_2], [10]], 
          ['Hindrance', [imp_2, imp_1], [6, 12]], ['Hindrance', [imp_2, imp_1], [6, 11]], 
          ['Lowlife', [imp_1], [16]] ],
    '5': [['Soldier', [imp_4], [2]], ['Soldier', [imp_4, imp_3], [2, 1]], ['Soldier', [imp_4, imp_2], [2, 4]], 
          ['Imp', [imp_3], [7]], ['Imp', [imp_3], [8]], 
          ['Deserter', [imp_3, imp_2], [4, 8]], ['Deserter', [imp_3, imp_2], [4, 7]], 
          ['Deserter', [imp_3, imp_2], [3, 10]], ['Deserter', [imp_3, imp_2], [3, 9]], 
          ['Servant', [imp_2], [14]], ['Servant', [imp_2], [13]] ],
    '6': [['Soldier', [imp_4], [5]], ['Soldier', [imp_4], [4]], 
          ['Outpost guard', [imp_4, imp_3, imp_2], [2, 6, 8]], ['Outpost guard', [imp_4, imp_3, imp_2], [2, 6, 7]], 
          ['Outpost guard', [imp_4, imp_3, imp_2], [2, 5, 8]], ['Outpost guard', [imp_4, imp_3, imp_2], [2, 5, 7]], 
          ['Patrol', [imp_4, imp_3], [3, 6]], ['Patrol', [imp_4, imp_3], [3, 5]], 
          ['Guard', [imp_4, imp_2], [3, 8]], ['Guard', [imp_4, imp_2], [3, 7]], 
          ['Imp', [imp_3], [11]], ['Imp', [imp_3], [10]], 
          ['Deserter', [imp_3, imp_2], [6, 12]], ['Deserter', [imp_3, imp_2], [6, 11]], 
          ['Servant', [imp_2], [16]] ],
    '7': [['Greater', [imp_5], [2]], ['Greater', [imp_5, imp_4], [2, 1]], ['Greater', [imp_5, imp_3], [2, 4]], 
          ['Soldier', [imp_4], [7]], ['Soldier', [imp_4], [8]], 
          ['Patrol', [imp_4, imp_3], [4, 8]], ['Patrol', [imp_4, imp_3], [4, 7]],
          ['Patrol', [imp_4, imp_3], [3, 10]], ['Patrol', [imp_4, imp_3], [3, 9]], 
          ['Imp', [imp_3], [14]], ['Imp', [imp_3], [13]] ],
    '8': [['Greater', [imp_5], [5]], ['Greater', [imp_5], [4]], 
          ['Guardian', [imp_5, imp_4, imp_3], [2, 6, 8]], ['Guardian', [imp_5, imp_4, imp_3], [2, 6, 7]], 
          ['Guardian', [imp_5, imp_4, imp_3], [2, 5, 8]], ['Guardian', [imp_5, imp_4, imp_3], [2, 5, 7]], 
          ['Escort', [imp_5, imp_4], [3, 6]], ['Escort', [imp_5, imp_4], [3, 5]], 
          ['Citizen', [imp_5, imp_3], [3, 8]], ['Citizen', [imp_5, imp_3], [3, 7]], 
          ['Soldier', [imp_4], [11]], ['Soldier', [imp_4], [10]], 
          ['Patrol', [imp_4, imp_3], [6, 12]], ['Patrol', [imp_4, imp_3], [6, 11]], 
          ['Imp', [imp_3], [16]] ],
    '9': [['General', [imp_6], [2]], ['General', [imp_6, imp_5], [2, 1]], ['General', [imp_6, imp_4], [2, 4]], 
          ['Greater', [imp_5], [7]], ['Greater', [imp_5], [8]], 
          ['Escort', [imp_5, imp_4], [4, 8]], ['Escort', [imp_5, imp_4], [4, 7]], 
          ['Escort', [imp_5, imp_4], [3, 10]], ['Escort', [imp_5, imp_4], [3, 9]], 
          ['Soldier', [imp_4], [14]], ['Soldier', [imp_4], [13]] ],
    '10': [['General', [imp_6], [5]], ['General', [imp_6], [4]], 
          ['Company', [imp_6, imp_5, imp_4], [2, 6, 8]], ['Company', [imp_6, imp_5, imp_4], [2, 6, 7]], 
          ['Company', [imp_6, imp_5, imp_4], [2, 5, 8]], ['Company', [imp_6, imp_5, imp_4], [2, 5, 7]], 
          ['Platoon', [imp_6, imp_5], [3, 6]], ['Platoon', [imp_6, imp_5], [3, 5]], 
          ['Troop', [imp_6, imp_4], [3, 8]], ['Troop', [imp_6, imp_4], [3, 7]], 
          ['Greater', [imp_5], [11]], ['Greater', [imp_5], [10]], 
          ['Escort', [imp_5, imp_4], [6, 12]], ['Escort', [imp_5, imp_4], [6, 11]], 
          ['Soldier', [imp_4], [16]] ],
    '11': [['Slave', [demon_1], [2]], ['Slave', [demon_1, imp_6], [2, 1]], ['Slave', [demon_1, imp_5], [2, 4]], 
          ['General', [imp_6], [7]], ['General', [imp_6], [8]], 
          ['Leader', [imp_6, imp_5], [4, 8]], ['Leader', [imp_6, imp_5], [4, 7]], 
          ['Leader', [imp_6, imp_5], [3, 10]], ['Leader', [imp_6, imp_5], [3, 9]], 
          ['Greater', [imp_5], [14]], ['Greater', [imp_5], [13]] ],
    '12': [['Slave', [demon_1], [5]], ['Slave', [demon_1], [4]], 
          ['Leader', [demon_1, imp_6, imp_5], [2, 6, 8]], ['Leader', [demon_1, imp_6, imp_5], [2, 6, 7]], 
          ['Leader', [demon_1, imp_6, imp_5], [2, 5, 8]], ['Leader', [demon_1, imp_6, imp_5], [2, 5, 7]], 
          ['General', [demon_1, imp_6], [3, 6]], ['General', [demon_1, imp_6], [3, 5]], 
          ['Greater', [demon_1, imp_5], [3, 8]], ['Greater', [demon_1, imp_5], [3, 7]], 
          ['General', [imp_6], [11]], ['General', [imp_6], [10]], 
          ['Leader', [imp_6, imp_5], [6, 12]], ['Leader', [imp_6, imp_5], [6, 11]], 
          ['Greater', [imp_5], [16]] ],
    '13': [['Lower one', [demon_2], [2]], ['Lower one', [demon_2, demon_1], [2, 1]], ['Lower one', [demon_2, imp_6], [2, 4]], 
          ['Slave', [demon_1], [7]], ['Slave', [demon_1], [8]], 
          ['General', [demon_1, imp_6], [4, 8]], ['General', [demon_1, imp_6], [4, 7]], 
          ['General', [demon_1, imp_6], [3, 10]], ['General', [demon_1, imp_6], [3, 9]], 
          ['General', [imp_6], [14]], ['General', [imp_6], [13]] ],
    '14': [['Lower one', [demon_2], [5]], ['Lower one', [demon_2], [4]], 
          ['Reinforcement', [demon_2, demon_1, imp_6], [2, 6, 8]], ['Reinforcement', [demon_2, demon_1, imp_6], [2, 6, 7]], 
          ['Reinforcement', [demon_2, demon_1, imp_6], [2, 5, 8]], ['Reinforcement', [demon_2, demon_1, imp_6], [2, 5, 7]], 
          ['Reinforcement', [demon_2, demon_1], [3, 6]], ['Reinforcement', [demon_2, demon_1], [3, 5]], 
          ['Reinforcement', [demon_2, imp_6], [3, 8]], ['Reinforcement', [demon_2, imp_6], [3, 7]], 
          ['Slave', [demon_1], [11]], ['Slave', [demon_1], [10]], 
          ['General', [demon_1, imp_6], [6, 12]], ['General', [demon_1, imp_6], [6, 11]], 
          ['General', [imp_6], [16]] ],
    '15': [['Demon', [demon_3], [2]], ['Demon', [demon_3, demon_2], [2, 1]], ['Demon', [demon_3, demon_1], [2, 4]], 
          ['Lower one', [demon_2], [7]], ['Lower one', [demon_2], [8]], 
          ['Lower one', [demon_2, demon_1], [4, 8]], ['Lower one', [demon_2, demon_1], [4, 7]], 
          ['Lower one', [demon_2, demon_1], [3, 10]], ['Lower one', [demon_2, demon_1], [3, 9]], 
          ['Slave', [demon_1], [14]], ['Slave', [demon_1], [13]] ],
    '16': [['Demon', [demon_3], [5]], ['Demon', [demon_3], [4]], 
          ['Citizen', [demon_3, demon_2, demon_1], [2, 6, 8]], ['Citizen', [demon_3, demon_2, demon_1], [2, 6, 7]], 
          ['Citizen', [demon_3, demon_2, demon_1], [2, 5, 8]], ['Citizen', [demon_3, demon_2, demon_1], [2, 5, 7]], 
          ['Citizen', [demon_3, demon_2], [3, 6]], ['Citizen', [demon_3, demon_2], [3, 5]], 
          ['Demon', [demon_3, demon_1], [3, 8]], ['Demon', [demon_3, demon_1], [3, 7]], 
          ['Lower one', [demon_2], [11]], ['Lower one', [demon_2], [10]], 
          ['Lower one', [demon_2, demon_1], [6, 12]], ['Lower one', [demon_2, demon_1], [6, 11]], 
          ['Slave', [demon_1], [16]] ],
    '17': [['Fighter', [demon_4], [2]], ['Fighter', [demon_4, demon_3], [2, 1]], ['Fighter', [demon_4, demon_2], [2, 4]], 
          ['Demon', [demon_3], [7]], ['Demon', [demon_3], [8]], 
          ['Citizen', [demon_3, demon_2], [4, 8]], ['Citizen', [demon_3, demon_2], [4, 7]], 
          ['Citizen', [demon_3, demon_2], [3, 10]], ['Citizen', [demon_3, demon_2], [3, 9]], 
          ['Lower one', [demon_2], [14]], ['Lower one', [demon_2], [13]] ],
    '18': [['Fighter', [demon_4], [5]], ['Fighter', [demon_4], [4]], 
          ['Trainee', [demon_4, demon_3, demon_2], [2, 6, 8]], ['Trainee', [demon_4, demon_3, demon_2], [2, 6, 7]], 
          ['Trainee', [demon_4, demon_3, demon_2], [2, 5, 8]], ['Trainee', [demon_4, demon_3, demon_2], [2, 5, 7]], 
          ['Post guard', [demon_4, demon_3], [3, 6]], ['Post guard', [demon_4, demon_3], [3, 5]], 
          ['Patrol', [demon_4, demon_2], [3, 8]], ['Patrol', [demon_4, demon_2], [3, 7]], 
          ['Demon', [demon_3], [11]], ['Demon', [demon_3], [10]], 
          ['Citizen', [demon_3, demon_2], [6, 12]], ['Citizen', [demon_3, demon_2], [6, 11]], 
          ['Lower one', [demon_2], [16]] ],
    '19': [['Higher one', [demon_5], [2]], ['Higher one', [demon_5, demon_4], [2, 1]], ['Higher one', [demon_5, demon_3], [2, 4]], 
          ['Fighter', [demon_4], [7]], ['Fighter', [demon_4], [8]], 
          ['Post guard', [demon_4, demon_3], [4, 8]], ['Post guard', [demon_4, demon_3], [4, 7]], 
          ['Post guard', [demon_4, demon_3], [3, 10]], ['Post guard', [demon_4, demon_3], [3, 9]], 
          ['Demon', [demon_3], [14]], ['Demon', [demon_3], [13]] ],
    '20': [['Higher one', [demon_5], [5]], ['Higher one', [demon_5], [4]], 
          ['Uncommoners', [demon_5, demon_4, demon_3], [2, 6, 8]], ['Uncommoners', [demon_5, demon_4, demon_3], [2, 6, 7]], 
          ['Uncommoners', [demon_5, demon_4, demon_3], [2, 5, 8]], ['Uncommoners', [demon_5, demon_4, demon_3], [2, 5, 7]], 
          ['Chokepost guard', [demon_5, demon_4], [3, 6]], ['Chokepost guard', [demon_5, demon_4], [3, 5]], 
          ['Citizen', [demon_5, demon_3], [3, 8]], ['Citizen', [demon_5, demon_3], [3, 7]], 
          ['Fighter', [demon_4], [11]], ['Fighter', [demon_4], [10]], 
          ['Post guard', [demon_4, demon_3], [6, 12]], ['Post guard', [demon_4, demon_3], [6, 11]], 
          ['Demon', [demon_3], [16]] ],
    '21': [['Guardian', [demon_6], [2]], ['Guardian', [demon_6, demon_5], [2, 1]], ['Guardian', [demon_6, demon_4], [2, 4]], 
          ['Higher one', [demon_5], [7]], ['Higher one', [demon_5], [8]], 
          ['Chokepost guard', [demon_5, demon_4], [4, 8]], ['Chokepost guard', [demon_5, demon_4], [4, 7]], 
          ['Chokepost guard', [demon_5, demon_4], [3, 10]], ['Chokepost guard', [demon_5, demon_4], [3, 9]], 
          ['Fighter', [demon_4], [14]], ['Fighter', [demon_4], [13]] ],
    '22': [['Guardian', [demon_6], [5]], ['Guardian', [demon_6], [4]], 
          ['Guard', [demon_6, demon_5, demon_4], [2, 6, 8]], ['Guard', [demon_6, demon_5, demon_4], [2, 6, 7]], 
          ['Guard', [demon_6, demon_5, demon_4], [2, 5, 8]], ['Guard', [demon_6, demon_5, demon_4], [2, 5, 7]], 
          ['Elite', [demon_6, demon_5], [3, 6]], ['Elite', [demon_6, demon_5], [3, 5]], 
          ['Squad', [demon_6, demon_4], [3, 8]], ['Squad', [demon_6, demon_4], [3, 7]], 
          ['Higher one', [demon_5], [11]], ['Higher one', [demon_5], [10]], 
          ['Chokepost guard', [demon_5, demon_4], [6, 12]], ['Chokepost guard', [demon_5, demon_4], [6, 11]], 
          ['Fighter', [demon_4], [16]] ],
    '23': [['Warlord', [demon_7], [2]], ['Warlord', [demon_7, demon_6], [2, 1]], ['Warlord', [demon_7, demon_5], [2, 4]], 
          ['Guardian', [demon_6], [7]], ['Guardian', [demon_6], [8]], 
          ['Elite', [demon_6, demon_5], [4, 8]], ['Elite', [demon_6, demon_5], [4, 7]], 
          ['Elite', [demon_6, demon_5], [3, 10]], ['Elite', [demon_6, demon_5], [3, 9]], 
          ['Higher one', [demon_5], [14]], ['Higher one', [demon_5], [13]] ],
    '24': [['Warlord', [demon_7], [5]], ['Warlord', [demon_7], [4]], 
          ['Leader', [demon_7, demon_6, demon_5], [2, 6, 8]], ['Leader', [demon_7, demon_6, demon_5], [2, 6, 7]], 
          ['Leader', [demon_7, demon_6, demon_5], [2, 5, 8]], ['Leader', [demon_7, demon_6, demon_5], [2, 5, 7]], 
          ['Platoon', [demon_7, demon_6], [3, 6]], ['Platoon', [demon_7, demon_6], [3, 5]], 
          ['Troop', [demon_7, demon_5], [3, 8]], ['Troop', [demon_7, demon_5], [3, 7]], 
          ['Guardian', [demon_6], [11]], ['Guardian', [demon_6], [10]], 
          ['Elite', [demon_6, demon_5], [6, 12]], ['Elite', [demon_6, demon_5], [6, 11]], 
          ['Higher one', [demon_5], [16]] ],
    }